### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Roboto-Extremo#15]
I'd like to see this project building the binaries using Travis Continuous Integration, and posting them to the `gh-pages` branch.

Happy to provide more details/context if this doesn't make sense.

**Comment by davelab6** [comment]
Curious to learn more about the status of this.

**Comment by dberlow** [comment]
Both extremo and Amstelvar repositories are now public and Using continuous integration.

**Comment by cjdunn** [comment]
@davelab6 Travis CI [has now been implemented](https://github.com/TypeNetwork/Roboto-Extremo/pull/22)

Anytime a commit for Roboto-Extremo is pushed to github, Travis will run the build script and test if the repo is building. If a build is successful on the master branch, Travis will push the updates to the gh-pages branch of the Roboto-Extremo repo. I’ve added a basic html proof which will use the latest fonts from the gh-pages branch, and you can see the proof via this URL:
https://typenetwork.github.io/Roboto-Extremo/proof/

Please let us know if this satisfies your requirements, thanks!

**Comment by dberlow** [comment]
The build requirements work look great, but I leave that to Dave to approve.

The proof requirements, more generally, we need to take up elsewhere.

But for this default, basic set of proofs, can you document the criteria you are using for; what instances are proofed and 
the order they are composed as pages in a single pdf?

Thanks.



On Jul 1, 2019, at 4:43 PM, CJ Dunn <notifications@github.com> wrote:

@davelab6 Travis CI has now been implemented

Anytime a commit for Roboto-Extremo is pushed to github, Travis will run the build script and test if the repo is building. If a build is successful on the master branch, Travis will push the updates to the gh-pages branch of the Roboto-Extremo repo. I’ve added a basic html proof which will use the latest fonts from the gh-pages branch, and you can see the proof via this URL:
https://typenetwork.github.io/Roboto-Extremo/proof/

Please let us know if this satisfies your requirements, thanks!
