### ISSUE TITLE
Build with opsz-default to opsz-min only

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Roboto-Extremo#23]
Since the fonttools instancer doesn't yet support clipping axis ranges, I'd like to request a build that only builds the design space from opsz-default to opsz-min. This will be helpful to show that 'non corner master' design spaces can be useful, with minimal filesize, with OT 1.8 :)

Ideally this will be part of the CI build process, so that its continually available as the glyph set and other axes are built out.

**Comment by dberlow** [comment]
So, just to be clear, 
   is this requesting a vf that’s just a 1/2 an opsz Axes, 
   or the design space that is included with opsz min?

And,
  Is this just a one-off demo,
  Of should we create a model of vfs with clipped spaces from most common to less common?

**Comment by dberlow** [comment]
SO,

In the mean time, can you 
  make and use a designspace 
  that creates Amstelvarroman-opszmin.ttf, 
      With one axis, opsz,
          containing only the default and opsz min,

**Comment by sannorozco** [comment]
Added RobotoExtremo-Roman-opszmin.ttf, with opsz axis, from opszmin to default.

**Comment by sannorozco** [comment]
hang on, updating.

**Comment by sannorozco** [comment]
Added RobotoExtremo-Roman-opszmin.ttf, with opsz axis, from opszmin to default.

**Comment by dberlow** [comment]
Extremo fonts folder.

**Comment by dberlow** [comment]
Please note location url and close
