### ISSUE TITLE
Proofs 2019-07-12

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Roboto-Extremo#27]
docs > Proofs > RobotoExtremo_pdfs_2019-07-12

Design Space ASCII-showing of 27 instances in the range of the design space
Regular WGL-comparisons of current default WGL with the original
Light ASCII-comparison of Light VF instance with the original

**Comment by cjdunn** [comment]
@pichotta This PR should include all the proofs you listed:
https://github.com/TypeNetwork/Roboto-Extremo/pull/30

**Comment by cjdunn** [comment]
@pichotta oops, you can disregard my last comment. Looks like you already added these proofs via your commit on 7/12:
https://github.com/TypeNetwork/Roboto-Extremo/commit/8a44262618b6ec117676caa13e5ad198adf68be3

I'll close the issue now, thanks.

**Comment by pichotta** [comment]
updated the Overlay proof "RobotoWGLRegular_OverlayUnicode_Orig vs Extremo_2019-07-17"

the new proof reflects the current outlines and updated Vietnamese accent positioning.
