### ISSUE TITLE
ASCII MONDAY Build

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto-Extremo#33]
Santiago, 
ASCII is done for three new Extremo axes.

Please add:
GRAD min and  max
YTAS  min and  max
YTDE  min and  max
to design space.

Give them each their parametric values from DELTA axes values.

And build, thanks.

**Comment by davelab6** [comment]
Thanks @dberlow - great stuff and loving the commit history, much more clear to follow what is happening these days :)

**Comment by dberlow** [comment]
Sanitago,

We are going to need a bigger designspace file and a new Var tomorrow.

Same masters and intermediates as Extremo, 
OPSZ
WGTH
WDTH

Renewed master:
Should have same values as Delta
GRAD min max

New Y trans masters:

Should have same values as Delta
YTDE min max   descenders
YTAS min max   ascenders

All must have same values for max and min, (as Delta?)
YTUC min max  Uppercase Ht.
YTLC min max lowercase ht.
YTFI min max Figure ht.

New X-transmasters Trisected masters, all must have same values for max and min. (as Delta?)
XTLC min max lowercase x-transparent
XTUC min max Uppercase x-transparent
XTFI min max Figures x-transparent

**Comment by sannorozco** [comment]
Yes, on it!

**Comment by sannorozco** [comment]
Updated Vf in repo with:

—OPSZ
—WGTH
—WDTH
—GRAD min max
—YTDE min max descenders
—YTAS min max ascenders
—YTUC min max Uppercase Ht
—YTLC min max lowercase ht
—YTFI min max Figure ht. (1 measured mew masters)
—XTLC min max lowercase x-transparent (n measured mew masters)
—XTUC min max Uppercase x-transparent (H measured mew masters)
—XTFI min max Figures x-transparent (0 measured mew masters)
