### ISSUE TITLE
List of initial designspace caps

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto-Extremo#36]
Santiago, or CJ now that it’s monday,

Capping instances. The ‘From’ is copied and ’becomes named’, which is then added to the Designspace.
From:                                               Becomes named:
opsz 144 wdth 100 wght 100 —    Opsz 144 wdth 100 wght 100 GRAD mIn
![F774C5C5-28E3-48A7-8991-5B8098D510AE](https://user-images.githubusercontent.com/1956494/62474702-7a25dd00-b771-11e9-9e49-1167b2de72a2.jpeg)

Which fixes the whole wght min incl. eg...
![AEE43B7D-DD33-4326-898C-BEAFF9CED6D8](https://user-images.githubusercontent.com/1956494/62474526-14395580-b771-11e9-9ce1-71175406fbb4.jpeg)

opsz 144 wdth 100 wght 900 —    opsz 144 wdth 100 wght 900 GRAD max
opsz 144 wdth 75 wght 400 —      opsz 144 wdth 75 wght 400 XTRA min
![227D778E-4AF6-4F7B-9F66-2488EF601BD2](https://user-images.githubusercontent.com/1956494/62474202-5f069d80-b770-11e9-8ca0-efe652aa699c.jpeg)

opsz 144 wdth 75 wght 900 —      opsz 144 wdth 75 wght 900 XTRA min

Some instances illustrated, check other issues for ongoing additions. will be needing to translate to design space and sources, then into a narrative and illustrated doc with examples, values in sheets and truevalues. 

But building soon documenting shortly after, so we can make sure the three registered axes and grad are all “safe” instances.

And we need to do this before trimming, capping or tailoring other axes.

**Comment by sannorozco** [comment]
On this now!

**Comment by dberlow** [comment]
Hey,
There are ascii contour fixes, edits done as marked on repo, and grad caps all waiting for remake and check By you.

I am going to run and close up my fonts first, and then go back to proofing until there is a new build. Let me know if that’s not going to be done by 10 a.m.

Thanks!

On Aug 5, 2019, at 8:41 AM, Santiago Orozco <notifications@github.com> wrote:

On this now!

**Comment by sannorozco** [comment]
Updated VF with capped instances:

opsz 144 wdth 100 wght 100 at:
—opsz 144 wdth 100 wght 100 GRAD mIn

opsz 144 wdth 100 wght 900 at:
—opsz 144 wdth 100 wght 900 GRAD max

opsz 144 wdth 75 wght 400 at:
—opsz 144 wdth 75 wght 400 XTLC min
—opsz 144 wdth 75 wght 400 XTUC min
—opsz 144 wdth 75 wght 400 XTFI min

opsz 144 wdth 75 wght 900 at:
—opsz 144 wdth 75 wght 900 XTLC min
—opsz 144 wdth 75 wght 900 XTUC min
—opsz 144 wdth 75 wght 900 XTFI min

**Comment by dberlow** [comment]
SO, issue #40 is next example for DC to approve.

**Comment by dberlow** [comment]
The capped instances of dissected XT need to be removed, a merged XTRA created, and then the listed axes caps made, per 2 pm meeting. Dissected XT, YO, and YT are to end hidden, only the YOPQ, XTRA and YOPQ remain, and these are capped and trimmed soon...

**Comment by sannorozco** [comment]
Capped instances removed and added to XTRA.
