### ISSUE TITLE
Greek Phi and Omega - uneven spacing

### ISSUE THREAD

**Issue by EbenSorkin** [TypeNetwork/Roboto-Extremo#404]
In some masters it looks like the spacing is uneven on the left and right side

<img width="294" alt="image" src="https://github.com/googlefonts/roboto-flex/assets/2181213/d3f7991d-b99d-4e51-9557-d95edc1ef71f">
<img width="817" alt="image" src="https://github.com/googlefonts/roboto-flex/assets/2181213/67bfbf4b-d15a-4990-9f31-05cf232f3027">
<img width="985" alt="image" src="https://github.com/googlefonts/roboto-flex/assets/2181213/4c7eae61-ce2a-4fb9-bc41-369dc3d80a00">

**Comment by dberlow** [comment]
I have checked all the masters and find no such quite obvious spacing errors in the sources of the "main" or "duovars". If these errors at the unidentified design space locations shown above are being caused elsewhere, I'm not sure how. Many of the glyphs here look offest to the left, with it being most obvious when symmetric is set between symmetric.

**Comment by kenmcd** [comment]
Roboto Flex v3.200.(2023-06-30).release
Master: :op=144,wt=700,gr=0,wd=100,sl=0,xo=96,yo=79,xt=468,yt=712,pa=514,pr=750,pm=-203,pe=738
Glyph: /uni03A6 or /Phi
LSB: 29
RSB: 88
This one appears to be a bit off-center. 
Only Roman version of this glyph I found off this much.
The Italics are a lot harder to judge.

![Greek Phi v3 200](https://github.com/googlefonts/roboto-flex/assets/844920/e7a89b51-1eb1-4b8d-9502-129e9ad73e18)

**Comment by EbenSorkin** [comment]
I found two. 

<img width="770" alt="image" src="https://github.com/googlefonts/roboto-flex/assets/2181213/700be694-7238-45b4-ad56-666c46cda875">

and 

<img width="788" alt="image" src="https://github.com/googlefonts/roboto-flex/assets/2181213/5eda2e7b-09e5-4634-9ef3-b25d30271ade">

**Comment by EbenSorkin** [comment]
It looks like the problem I saw at first was from an older version and nearly all instances of the issue are dealt with now.

**Comment by davelab6** [comment]
Then let's close this issue :)
