### ISSUE TITLE
Lowercase extender trimming

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto-Extremo#41]
Trims:
opsz 144 wdth 100 wght 900 YTAS 706 to opsz 144 wdth 100 wght 900 YTAS min
opsz 144 wdth 100 wght 900 YTDE -167 to opsz 144 wdth 100 wght 900 YTDE min

Fix: figure 2, opsz 144 wdth 100 wght 100 GRAD 0.91

**Comment by sannorozco** [comment]
Added _opsz 144 wdth 100 wght 900 YTAS 706_ at:
—opsz 144 wdth 100 wght 900 YTAS min

Added _opsz 144 wdth 100 wght 900 YTDE -167_ at:
—opsz 144 wdth 100 wght 900 YTDE min

Corrected fig 2 at _opsz 144 wdth 100 wght 100 GRAD 0.91_
