### ISSUE TITLE
Backward compatibility issue [ver 3.1 → 3.2]

### ISSUE THREAD

**Issue by 4beraser** [TypeNetwork/Roboto-Extremo#418]
Hi, thanks for the great font!

I get an issue when using previous version on Adobe Photoshop. After upgrading to ver 3.200, it won't recognize any settings of ver 3.1, this has caused some colleague sync issue. 

I think it should be informed to users, if the font doesn't have backward compatibility.

**ver 3.100:**
![image](https://github.com/googlefonts/roboto-flex/assets/139553898/f3bc00f5-b9f4-4ec1-b593-ddfe287354f1)
**ver 3.200:**
![image](https://github.com/googlefonts/roboto-flex/assets/139553898/71f5b245-0553-4db8-97bc-f44a869a7db9)

**Comment by davelab6** [comment]
@4beraser sadly this is a problem with that application so you'll need to report it to Adobe, because the font is set up to work across versions... I'm sorry
