### ISSUE TITLE
Fresh proofs today

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto-Extremo#44]
CJ or SO,

CSS proofing advances a space, but is not ready now.
  (See: https://github.com/TypeNetwork/videoproof/issues/12 for details)

We WILL need pdf proofs of 27 styles of extremo added as a separate folder from the last versions of the proofs, and the client should be notified via repo.

The registered axes, ascii, is complete for the default 27 styles of the prev. proofs.

Pretty urgent today, 

Let me know, thanks.

**Comment by cjdunn** [comment]
@dberlow OK, I'm working on this now. I'm planning on making ASCII proofs for the 27 proofs. If you need anything else please let me know, thanks.

**Comment by cjdunn** [comment]
The proofs have been added via: 
https://github.com/TypeNetwork/Roboto-Extremo/pull/45
