### ISSUE TITLE
Outlines: Quadratic Path Directions

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Roboto-Extremo#49]
In these styles the clockwise path direction of the /degree is different from the default Regular.
   RobotoExtremo wdthmax
   RobotoExtremo opsz18-wghtmin-wdthmin
   RobotoExtremo wdthmin
   RobotoExtremo opsz18wght700wdthmin
   RobotoExtremo wghtmax 

In this one style the contour and path direction of /ordmasculine differs from the other masters.
   RobotoExtremo wghtmax

**Comment by dberlow** [comment]
RobotoExtremo wdthmax _fixed_
RobotoExtremo opsz18-wghtmin-wdthmin  _fixed_
RobotoExtremo wdthmin  _fixed_
RobotoExtremo opsz18wght700wdthmin  _fixed_
RobotoExtremo wghtmax  _was not wrong, please check file name_

/ordmasculine differs from the other masters.
RobotoExtremo wghtmax  _fixed_
