### ISSUE TITLE
slnt values

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto-Extremo#82]
These are not showing in typetools as 0 at the default, making them show up in show parameters
![28CF04F4-8460-49E8-B6AA-F9D38FA6D1C3](https://user-images.githubusercontent.com/1956494/74649712-1a5fb400-514e-11ea-9cfd-8be86c3866b9.png)

**Comment by sannorozco** [comment]
This is corrected now in new build.

**Comment by dberlow** [comment]
Thank you!
