### ISSUE TITLE
Components: Rotated or Scaled

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Roboto-Extremo#83]
In the 1A-drawing/Mains folder. These glyphs in these sources have components which are rotated or scaled.

I could make this fix with a script by decomposing if requested.  If so, any other .ufos in these folders?
_Duovars
Parametric Axes
Quadravars
Trivars_

'RobotoExtremo opsz144-wght400-slnt-1'
	 fraction in percent
	 commaaccentcomb in gcommaaccent
	 
'RobotoExtremo wght100' path='
	 commaaccentcomb in gcommaaccent
	 
'RobotoExtremo Regular'
	 commaaccentcomb in gcommaaccent
	 
'RobotoExtremo wdth25'
	 commaaccentcomb in gcommaaccent
	 
'RobotoExtremo wdth151'
	 commaaccentcomb in gcommaaccent
	 
'RobotoExtremo opsz14-wght100-slnt-10.00' path='
	 commaaccentcomb in gcommaaccent
	 
'RobotoExtremo opsz144'
	 commaaccentcomb in gcommaaccent
	 
'RobotoExtremo GRAD1'
	 commaaccentcomb in gcommaaccent
	 
'RobotoExtremo Slant'
	 fraction in percent
	 commaaccentcomb in gcommaaccent
	 
'RobotoExtremo opsz8'
	 commaaccentcomb in gcommaaccent
	 
'Slim4slant wght_400.00_opsz_144.00_slnt_-10.00' 
	 commaaccentcomb in gcommaaccent
	 
'RobotoExtremo opsz144-wght400-slnt-1'
	 fraction in percent
	 commaaccentcomb in gcommaaccent
	 
'Slim4slant wght_100.00_opsz_14.00_slnt_-10.00'
	 fraction in percent
	 commaaccentcomb in gcommaaccent
	 
'Slim4slant wght_100.00_opsz_14.00_slnt_1.00'
	 commaaccentcomb in gcommaaccent
	 
'Slim4slant wght_100.00_opsz_14.00_slnt_-1.00'
	 fraction in percent
	 commaaccentcomb in gcommaaccent
	 
'RobotoExtremo opsz14-wght100-slnt-10.00'
	 fraction in percent
	 commaaccentcomb in gcommaaccent
	 
'RobotoExtremo wght900' 
	 commaaccentcomb in gcommaaccent
	 
'RobotoExtremo GRAD-1' 
	 commaaccentcomb in gcommaaccent

**Comment by dberlow** [comment]
Wrong project, thanks.
