### ISSUE TITLE
Extremo ASCII delivery notes

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Roboto-Extremo#9]
Dave,

Based on a tentative "yes" the the breadth of the RobotoExtremo design space, a prototype was requested for delivery to Material Design for testing. 

That font is now in the "fonts" folder.

In the proofs folder are the first set of proofs for this Roboto Extremo variable font

This proof is big enough to contain all the glyphs of more than 30 styles on one page for zooming and marking, glyphs, styles and axes with comments, or just to see them together.

Further proofs as required for future deliveries will be added as software is developed to generated such proofs.

The font currently contains 3 axes;
   1. wdth
   2. wght
   3. opsz

The Glyph repertoire contains ASCI glyphs throughout 
the space

There is an exception of a few of the lower useage glyphs
in the boldest and most condensed of the largest optical size, 
These are only as bold as a previous version.

The font is recommended for use with browsers, more than
with applications like illustrator.

**Comment by cjdunn** [comment]
Latest proofs were added by @pichotta via this commit:
https://github.com/TypeNetwork/Roboto-Extremo/commit/8a44262618b6ec117676caa13e5ad198adf68be3

I believe this issue can be closed now.
